package org.usfirst.frc.team1736.robot;

public enum AutoModes {
	LEFT_SWITCH_FROM_CENTER, 
	LEFT_SWITCH_FROM_LEFT, 
	RIGHT_SWITCH_FROM_CENTER, 
	RIGHT_SWITCH_FROM_RIGHT,
	LEFT_SCALE_FROM_LEFT,
	RIGHT_SCALE_FROM_RIGHT,
	CROSS_BASELINE,
	CROSS_BASELINE_FROM_CENTER,
	TEST_MODE_1,
	TEST_MODE_2,
	DO_NOTHING,
	TWO_CUBE_LEFT,
	TWO_CUBE_RIGHT,
	TWO_CUBE_LEFT_FROM_CENTER,
	TWO_CUBE_RIGHT_FROM_CENTER,
	UNKNOWN,
	SCALE_CROSSOVER_LEFT,
	SCALE_CROSSOVER_RIGHT
	
}
